### ISSUE TITLE
External converter no longer works on Zigbee2MQTT with update to 2.8.0

### ISSUE THREAD

**Issue by dane-io** [Stickman-Solutions/ESP_Stickbee#4]
### Description
After updating Zigbee2MQTT to 2.8.0 from 2.7.2, Zigbee2MQTT reports the following error:

> [2026-02-08 20:20:25] error: 	z2m: Invalid external converter 'ESP_Stickbee.js' was ignored and renamed to prevent interference with Zigbee2MQTT. (Cannot find module '/config/zigbee2mqtt/external_converters/node_modules/zigbee-herdsman-converters/dist/lib/ota.js')
[2026-02-08 20:20:25] debug: 	z2m: Error: Cannot find module '/config/zigbee2mqtt/external_converters/node_modules/zigbee-herdsman-converters/dist/lib/ota.js'
    at createEsmNotFoundErr (node:internal/modules/cjs/loader:1419:15)
    at finalizeEsmResolution (node:internal/modules/cjs/loader:1408:15)
    at resolveExports (node:internal/modules/cjs/loader:650:14)
    at Function._findPath (node:internal/modules/cjs/loader:717:31)
    at Function._resolveFilename (node:internal/modules/cjs/loader:1369:27)
    at defaultResolveImpl (node:internal/modules/cjs/loader:1025:19)
    at resolveForCJSWithHooks (node:internal/modules/cjs/loader:1030:22)
    at Function._load (node:internal/modules/cjs/loader:1192:37)
    at TracingChannel.traceSync (node:diagnostics_channel:328:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:237:24)

### Cause and workaround
This is caused by an unused import in the converter. The following workaround can be applied:

1. Comment out the following line in the converter:
`const ota = require('zigbee-herdsman-converters/lib/ota');`
1. It should look like this after:
`//const ota = require('zigbee-herdsman-converters/lib/ota');`

**Comment by dane-io** [comment]
Fixed with 5d6579f
